[pytest]

testpaths = tests
python_files = test_*.py

norecursedirs =
    airflow
    airflow/logs
    venv
    __pycache__
    .git
    htmlcov
    .pytest_cache

filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning